--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA STUDENT_140!

CREATE TABLE STUDENT_140.STUDENT (
		REGNO VARCHAR(30) NOT NULL,
		NAME VARCHAR(30) NOT NULL,
		MAJOR VARCHAR(30) NOT NULL,
		BDATE VARCHAR(10) NOT NULL
	)
	DATA CAPTURE NONE!

CREATE TABLE STUDENT_140.COURSE (
		COURSE_ID VARCHAR(30) NOT NULL,
		CNAME VARCHAR(30),
		DEPT VARCHAR(30)
	)
	DATA CAPTURE NONE!

CREATE TABLE STUDENT_140.ENROLL (
		REGNO VARCHAR(30),
		COURSE_ID VARCHAR(30),
		MARKS DOUBLE
	)
	DATA CAPTURE NONE!

CREATE TABLE STUDENT_140.BOOK_ADOPTION (
		COURSE_ID VARCHAR(30),
		SEM VARCHAR(5),
		ISBN VARCHAR(30)
	)
	DATA CAPTURE NONE!

CREATE TABLE STUDENT_140.TEXT (
		BOOK_ISBN VARCHAR(30) NOT NULL,
		TITLE VARCHAR(30),
		PUBLISHER VARCHAR(30),
		AUTHOR VARCHAR(30)
	)
	DATA CAPTURE NONE!

ALTER TABLE STUDENT_140.STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY
	(REGNO)!

ALTER TABLE STUDENT_140.COURSE ADD CONSTRAINT COURSE_PK PRIMARY KEY
	(COURSE_ID)!

ALTER TABLE STUDENT_140.TEXT ADD CONSTRAINT TEXT_PK PRIMARY KEY
	(BOOK_ISBN)!

ALTER TABLE STUDENT_140.ENROLL ADD CONSTRAINT ENROLL_STUDENT_FK FOREIGN KEY
	(REGNO)
	REFERENCES STUDENT_140.STUDENT
	(REGNO)
	ON DELETE CASCADE!

ALTER TABLE STUDENT_140.ENROLL ADD CONSTRAINT ENROLL_COURSE_FK FOREIGN KEY
	(COURSE_ID)
	REFERENCES STUDENT_140.COURSE
	(COURSE_ID)
	ON DELETE CASCADE!

ALTER TABLE STUDENT_140.BOOK_ADOPTION ADD CONSTRAINT BOOK_ADOPTION_TEXT_FK FOREIGN KEY
	(ISBN)
	REFERENCES STUDENT_140.TEXT
	(BOOK_ISBN)
	ON DELETE CASCADE!

ALTER TABLE STUDENT_140.BOOK_ADOPTION ADD CONSTRAINT BOOK_ADOPTION_COURSE_FK FOREIGN KEY
	(COURSE_ID)
	REFERENCES STUDENT_140.COURSE
	(COURSE_ID)
	ON DELETE CASCADE!

