--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA PRODUCT_140!

CREATE TABLE PRODUCT_140.PRODUCT (
		PID VARCHAR(30) DEFAULT NULL NOT NULL,
		PNAME VARCHAR(30)
	)
	DATA CAPTURE NONE!

CREATE TABLE PRODUCT_140.SUPPLIER (
		SID VARCHAR(30) DEFAULT NULL NOT NULL,
		SNAME VARCHAR(30)
	)
	DATA CAPTURE NONE!

CREATE TABLE PRODUCT_140.SUPPLY (
		SID VARCHAR(30),
		PID VARCHAR(30),
		QTY DOUBLE
	)
	DATA CAPTURE NONE!

ALTER TABLE PRODUCT_140.PRODUCT ADD CONSTRAINT PRODUCT_PK PRIMARY KEY
	(PID)!

ALTER TABLE PRODUCT_140.SUPPLIER ADD CONSTRAINT SUPPLIER_PK PRIMARY KEY
	(SID)!

ALTER TABLE PRODUCT_140.SUPPLY ADD CONSTRAINT SUPPLY_PRODUCT_FK FOREIGN KEY
	(PID)
	REFERENCES PRODUCT_140.PRODUCT
	(PID)
	ON DELETE CASCADE!

ALTER TABLE PRODUCT_140.SUPPLY ADD CONSTRAINT SUPPLY_SUPPLIER_FK FOREIGN KEY
	(SID)
	REFERENCES PRODUCT_140.SUPPLIER
	(SID)
	ON DELETE CASCADE!

